more detailed status messages on success and fail

diff --git a/.local/bin/conv b/.local/bin/conv
--- a/.local/bin/conv
+++ b/.local/bin/conv
@@ -8,7 +8,6 @@ which -s ebook-convert || { echo "ebook-convert not found."; exit 1; }
 files=("${@:1:$#-1}")
 convert_to="${@: -1}"
 
-
 for convert_from in "${files[@]}"; do
     [ -f "$convert_from" ] || { echo "$convert_from not found."; exit 1; }
 
@@ -18,21 +17,30 @@ for convert_from in "${files[@]}"; do
     case "$convert_to" in
         jpg|png|webp|gif)
             # Image conversion
-            magick "$convert_from" "$filename.$convert_to"
+            # magick "$convert_from" "$filename.$convert_to"
+            # echo "Converting $convert_from to $filename.$convert_to"
             echo "Converting $convert_from to $filename.$convert_to"
+            magick "$convert_from" "$filename.$convert_to" \
+                && echo -e "\tDone." \
+                || echo -e "\tConversion failed."
             ;;
         pdf)
             # Document conversion
             if [ "$convert_from_extension" = "docx" ] || [ "$convert_from_extension" = "odt" ]; then
-                soffice --headless --convert-to pdf "$convert_from"
                 echo "Converting $convert_from to $filename.pdf"
+                soffice --headless --convert-to pdf "$convert_from" \
+                    && echo -e "\tDone." \
+                    || echo -e "\tConversion failed."
             elif [ "$convert_from_extension" = "epub" ]; then
-                ebook-convert "$convert_from" "$filename.pdf"
                 echo "Converting $convert_from to $filename.pdf"
+                ebook-convert "$convert_from" "$filename.pdf" \
+                    && echo -e "\tDone." \
+                    || echo -e "\tConversion failed."
             fi
             ;;
         *)
             echo "Unsupported format: $convert_to"
             exit 1
+            ;;
     esac
 done
